### ISSUE TITLE
Use a standard for the Input directory 

### ISSUE THREAD

**Issue by sirspock** [mintproject/MINT-Transformation#82]
To me, it seems there is not a standard about the configuration.

Some data transformations use the key `input_dir`, `grid_dir` or `gldas_path`.

This makes the integration with DAME hard.

```
    inputs:
      layer: 1
      input_dir: "/tmp/demo/input/isric_soil"
```

```
    inputs:
      grid_dir: "/data/mint/gpm_grid_lol_kuru"
      date_regex: '3B-HHR-E.MS.MRG.3IMERG.(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})'
      output_file: "/data/mint/lol_kuru/climate_all.rts"
```

```
  gldas2cycles_func:
    comment: GLDAS2Cycles adapter
    adapter: funcs.Gldas2CyclesFunc
    inputs:
      start_date: "2000-01-01"
      end_date: "2000-01-01"
      gldas_path: "/tmp/input/gldas/"
      output_path: "/tmp/output/"
      output_prefix: "prefix"
      latitude: -1 # use coord_file when lat = -1 or long = -1
      longitude: -1 # use coord_file when lat = -1 or long = -1
      coord_file: "/tmp/input/oromia.csv"
```
