### ISSUE TITLE
More friendly version config files 

### ISSUE THREAD

**Issue by minhptx** [mintproject/MINT-Transformation#83]
@raunaqtri1 @binh-vu 

We need to integrate our transformation pipelines into [DAME]
(http://mint-project.info/products/model/#desktop-appliation-for-model-execution-dame). So we need a more user-friendly version of our YAML so that DAME can show to the users.

Can we add some new fields to the YAML file ?

1. description: should be the description for the whole pipeline

I'll update the list after I get more request from them.

**Comment by raunaqtri1** [comment]
@minhptx, there is already a description key for the whole pipeline. It is optional and that's why never used. For example, you can have a YAML config like this:

```
version: "1"
description: Transform ISRIC soil files to rts/rti files that can be used as input for Topoflow. Perform cropping, regridding and resampling using GDAL.
adapters:
  tf_soil:
    comment: My topoflow soil write adapter
    adapter: funcs.Topoflow4SoilWriteFunc
    inputs:
      layer: 1
      input_dir: "/tmp/demo/input/isric_soil"
      output_dir: "/tmp/demo/output/isric_soil"
      DEM_bounds: "34.221249999999, 7.362083333332, 36.446249999999, 9.503749999999"
      DEM_xres_arcsecs: "30"
      DEM_yres_arcsecs: "30"
```
